name: hqpinn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - pytorch
  - pip
  - jupyterlab
  - ipywidgets
  - pip:
      - pennylane
      - pennylane-qiskit
